#ifdef MIN_VERSION_base
#include "qprelude/types-unqualified/packages/base.inc"
#endif

#ifdef MIN_VERSION_containers
#include "qprelude/types-unqualified/packages/containers.inc"
#endif

#ifdef MIN_VERSION_dlist
#include "qprelude/types-unqualified/packages/dlist.inc"
#endif

#ifdef MIN_VERSION_text
#include "qprelude/types-unqualified/packages/text.inc"
#endif

#ifdef MIN_VERSION_unordered_containers
#include "qprelude/types-unqualified/packages/unordered-containers.inc"
#endif
