#ifdef MIN_VERSION_base
#include "qprelude/qualified-alpha/packages/base.inc"
#endif

#ifdef MIN_VERSION_binary
#include "qprelude/qualified-alpha/packages/binary.inc"
#endif

#ifdef MIN_VERSION_bytestring
#include "qprelude/qualified-alpha/packages/bytestring.inc"
#endif

#ifdef MIN_VERSION_containers
#include "qprelude/qualified-alpha/packages/containers.inc"
#endif

#ifdef MIN_VERSION_deepseq
#include "qprelude/qualified-alpha/packages/deepseq.inc"
#endif

#ifdef MIN_VERSION_dlist
#include "qprelude/qualified-alpha/packages/dlist.inc"
#endif

#ifdef MIN_VERSION_mtl
#include "qprelude/qualified-alpha/packages/mtl.inc"
#endif

#ifdef MIN_VERSION_semigroups
#include "qprelude/qualified-alpha/packages/semigroups.inc"
#endif

#ifdef MIN_VERSION_split
#include "qprelude/qualified-alpha/packages/split.inc"
#endif

#ifdef MIN_VERSION_storablevector
#include "qprelude/qualified-alpha/packages/storablevector.inc"
#endif

#ifdef MIN_VERSION_tagged
#include "qprelude/qualified-alpha/packages/tagged.inc"
#endif

#ifdef MIN_VERSION_text
#include "qprelude/qualified-alpha/packages/text.inc"
#endif

#ifdef MIN_VERSION_transformers
#include "qprelude/qualified-alpha/packages/transformers.inc"
#endif

#ifdef MIN_VERSION_unordered_containers
#include "qprelude/qualified-alpha/packages/unordered-containers.inc"
#endif

#ifdef MIN_VERSION_unsafe
#include "qprelude/qualified-alpha/packages/unsafe.inc"
#endif

#ifdef MIN_VERSION_vector
#include "qprelude/qualified-alpha/packages/vector.inc"
#endif
