#ifdef MIN_VERSION_aeson
#include "qprelude/fully/packages/aeson.inc"
#endif

#ifdef MIN_VERSION_array
#include "qprelude/fully/packages/array.inc"
#endif

#ifdef MIN_VERSION_async
#include "qprelude/fully/packages/async.inc"
#endif

#ifdef MIN_VERSION_attoparsec
#include "qprelude/fully/packages/attoparsec.inc"
#endif

#ifdef MIN_VERSION_base64_bytestring
#include "qprelude/fully/packages/base64-bytestring.inc"
#endif

#ifdef MIN_VERSION_binary
#include "qprelude/fully/packages/binary.inc"
#endif

#ifdef MIN_VERSION_blaze_builder
#include "qprelude/fully/packages/blaze-builder.inc"
#endif

#ifdef MIN_VERSION_bytestring
#include "qprelude/fully/packages/bytestring.inc"
#endif

#ifdef MIN_VERSION_Cabal
-- #include "qprelude/fully/packages/Cabal.inc"
#endif

#ifdef MIN_VERSION_case_insensitive
#include "qprelude/fully/packages/case-insensitive.inc"
#endif

#ifdef MIN_VERSION_cereal
#include "qprelude/fully/packages/cereal.inc"
#endif

#ifdef MIN_VERSION_cmdargs
#include "qprelude/fully/packages/cmdargs.inc"
#endif

#ifdef MIN_VERSION_conduit
#include "qprelude/fully/packages/conduit.inc"
#endif

#ifdef MIN_VERSION_containers
#include "qprelude/fully/packages/containers.inc"
#endif

#ifdef MIN_VERSION_criterion
#include "qprelude/fully/packages/criterion.inc"
#endif

#ifdef MIN_VERSION_data_default
#include "qprelude/fully/packages/data-default.inc"
#endif

#ifdef MIN_VERSION_deepseq
#include "qprelude/fully/packages/deepseq.inc"
#endif

#ifdef MIN_VERSION_directory
#include "qprelude/fully/packages/directory.inc"
#endif

#ifdef MIN_VERSION_dlist
#include "qprelude/fully/packages/dlist.inc"
#endif

#ifdef MIN_VERSION_doctest
#include "qprelude/fully/packages/doctest.inc"
#endif

#ifdef MIN_VERSION_either
#include "qprelude/fully/packages/either.inc"
#endif

#ifdef MIN_VERSION_exceptions
#include "qprelude/fully/packages/exceptions.inc"
#endif

#ifdef MIN_VERSION_extra
#include "qprelude/fully/packages/extra.inc"
#endif

#ifdef MIN_VERSION_filepath
#include "qprelude/fully/packages/filepath.inc"
#endif

#ifdef MIN_VERSION_hashable
#include "qprelude/fully/packages/hashable.inc"
#endif

#ifdef MIN_VERSION_haskeline
#include "qprelude/fully/packages/haskeline.inc"
#endif

#ifdef MIN_VERSION_hoopl
#include "qprelude/fully/packages/hoopl.inc"
#endif

#ifdef MIN_VERSION_hpc
#include "qprelude/fully/packages/hpc.inc"
#endif

#ifdef MIN_VERSION_hspec
#include "qprelude/fully/packages/hspec.inc"
#endif

#ifdef MIN_VERSION_http_conduit
#include "qprelude/fully/packages/http-conduit.inc"
#endif

#ifdef MIN_VERSION_HTTP
#include "qprelude/fully/packages/HTTP.inc"
#endif

#ifdef MIN_VERSION_http_types
#include "qprelude/fully/packages/http-types.inc"
#endif

#ifdef MIN_VERSION_HUnit
#include "qprelude/fully/packages/HUnit.inc"
#endif

#ifdef MIN_VERSION_interger_gmp
#include "qprelude/fully/packages/interger-gmp.inc"
#endif

#ifdef MIN_VERSION_lens
#include "qprelude/fully/packages/lens.inc"
#endif

#ifdef MIN_VERSION_monad_control
#include "qprelude/fully/packages/monad-control.inc"
#endif

#ifdef MIN_VERSION_mtl
#include "qprelude/fully/packages/mtl.inc"
#endif

#ifdef MIN_VERSION_multistate
#include "qprelude/fully/packages/multistate.inc"
#endif

#ifdef MIN_VERSION_network
#include "qprelude/fully/packages/network.inc"
#endif

#ifdef MIN_VERSION_network_uri
#include "qprelude/fully/packages/network-uri.inc"
#endif

#ifdef MIN_VERSION_optparse_applicative
#include "qprelude/fully/packages/optparse-applicative.inc"
#endif

#ifdef MIN_VERSION_parallel
#include "qprelude/fully/packages/parallel.inc"
#endif

#ifdef MIN_VERSION_parsec
#include "qprelude/fully/packages/parsec.inc"
#endif

#ifdef MIN_VERSION_pretty
#include "qprelude/fully/packages/pretty.inc"
#endif

#ifdef MIN_VERSION_primitive
#include "qprelude/fully/packages/primitive.inc"
#endif

#ifdef MIN_VERSION_process
#include "qprelude/fully/packages/process.inc"
#endif

#ifdef MIN_VERSION_QuickCheck
#include "qprelude/fully/packages/QuickCheck.inc"
#endif

#ifdef MIN_VERSION_random
#include "qprelude/fully/packages/random.inc"
#endif

#ifdef MIN_VERSION_resourcet
#include "qprelude/fully/packages/resourcet.inc"
#endif

#ifdef MIN_VERSION_safe
#include "qprelude/fully/packages/safe.inc"
#endif

#ifdef MIN_VERSION_scientific
#include "qprelude/fully/packages/scientific.inc"
#endif

#ifdef MIN_VERSION_semigroups
#include "qprelude/fully/packages/semigroups.inc"
#endif

#ifdef MIN_VERSION_split
#include "qprelude/fully/packages/split.inc"
#endif

#ifdef MIN_VERSION_stm
#include "qprelude/fully/packages/stm.inc"
#endif

#ifdef MIN_VERSION_storablevector
#include "qprelude/fully/packages/storablevector.inc"
#endif

#ifdef MIN_VERSION_syb
#include "qprelude/fully/packages/syb.inc"
#endif

#ifdef MIN_VERSION_tagged
#include "qprelude/fully/packages/tagged.inc"
#endif

#ifdef MIN_VERSION_tasty_hunit
#include "qprelude/fully/packages/tasty-hunit.inc"
#endif

#ifdef MIN_VERSION_tasty
#include "qprelude/fully/packages/tasty.inc"
#endif

#ifdef MIN_VERSION_tasty_quickcheck
#include "qprelude/fully/packages/tasty-quickcheck.inc"
#endif

#ifdef MIN_VERSION_template_haskell
#include "qprelude/fully/packages/template-haskell.inc"
#endif

#ifdef MIN_VERSION_terminfo
#include "qprelude/fully/packages/terminfo.inc"
#endif

#ifdef MIN_VERSION_test_framework_hunit
#include "qprelude/fully/packages/test-framework-hunit.inc"
#endif

#ifdef MIN_VERSION_test_framework
#include "qprelude/fully/packages/test-framework.inc"
#endif

#ifdef MIN_VERSION_text
#include "qprelude/fully/packages/text.inc"
#endif

#ifdef MIN_VERSION_time
#include "qprelude/fully/packages/time.inc"
#endif

#ifdef MIN_VERSION_transformers
#include "qprelude/fully/packages/transformers.inc"
#endif

#ifdef MIN_VERSION_unix
#include "qprelude/fully/packages/unix.inc"
#endif

#ifdef MIN_VERSION_unordered_containers
#include "qprelude/fully/packages/unordered-containers.inc"
#endif

#ifdef MIN_VERSION_unsafe
#include "qprelude/fully/packages/unsafe.inc"
#endif

#ifdef MIN_VERSION_utf8_string
#include "qprelude/fully/packages/utf8-string.inc"
#endif

#ifdef MIN_VERSION_vector
#include "qprelude/fully/packages/vector.inc"
#endif

#ifdef MIN_VERSION_wai
#include "qprelude/fully/packages/wai.inc"
#endif

#ifdef MIN_VERSION_xhtml
#include "qprelude/fully/packages/xhtml.inc"
#endif

#ifdef MIN_VERSION_base
#include "qprelude/fully/packages/base.inc"
#endif
