#ifdef MIN_VERSION_array
#include "qprelude/fully/packages/array.inc"
#endif

#include "qprelude/fully/packages/base.inc"

#ifdef MIN_VERSION_binary
#include "qprelude/fully/packages/binary.inc"
#endif

#ifdef MIN_VERSION_bytestring
#include "qprelude/fully/packages/bytestring.inc"
#endif

#ifdef MIN_VERSION_containers
#include "qprelude/fully/packages/containers.inc"
#endif

#ifdef MIN_VERSION_deepseq
#include "qprelude/fully/packages/deepseq.inc"
#endif

#ifdef MIN_VERSION_directory
#include "qprelude/fully/packages/directory.inc"
#endif

#ifdef MIN_VERSION_filepath
#include "qprelude/fully/packages/filepath.inc"
#endif

#ifdef MIN_VERSION_haskeline
#include "qprelude/fully/packages/haskline.inc"
#endif

#ifdef MIN_VERSION_hoopl
#include "qprelude/fully/packages/hoopl.inc"
#endif

#ifdef MIN_VERSION_hpc
#include "qprelude/fully/packages/hpc.inc"
#endif

#ifdef MIN_VERSION_integer_gmp
#include "qprelude/fully/packages/integer-gmp.inc"
#endif

#ifdef MIN_VERSION_pretty
#include "qprelude/fully/packages/pretty.inc"
#endif

#ifdef MIN_VERSION_process
#include "qprelude/fully/packages/process.inc"
#endif

#ifdef MIN_VERSION_template_haskell
#include "qprelude/fully/packages/template-haskell.inc"
#endif

#ifdef MIN_VERSION_terminfo
#include "qprelude/fully/packages/terminfo.inc"
#endif

#ifdef MIN_VERSION_time
#include "qprelude/fully/packages/time.inc"
#endif

#ifdef MIN_VERSION_transformers
#include "qprelude/fully/packages/transformers.inc"
#endif

#ifdef MIN_VERSION_unix
#include "qprelude/fully/packages/unix.inc"
#endif

#ifdef MIN_VERSION_xhtml
#include "qprelude/fully/packages/xhtml.inc"
#endif
